Repository Sayantan500/HTS-TicketsDataManagement, pull requests merged in 2023-04, with the labels that each got.

#2 ticket entities and postmapping
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/TicketController.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/entities/Ticket.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/entities/TicketDocument.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/entities/TicketRequest.java
Labels: functionality

#4 Connected MongoDb and provided get and save functionalities to system
  pom.xml
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/persistence/Database.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/persistence/mongo_db/MongoDB.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/persistence/mongo_db/MongoDBConfig.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/utilities/LoggingUtils.java
Labels: enhancement

#10 Generate Id for ticket
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/AppVariablesBeans.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/TicketController.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/utilities/IdGenerator.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/utilities/Utilities.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/utilities/UtilitiesImpl.java
Labels: enhancement

#11 Added issue_id to ticket
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/TicketController.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/entities/TicketRequest.java
Labels: bug

#13 Added logging utility
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/TicketController.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/exceptions_handling/handlers/RequestExceptionHandlers.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/exceptions_handling/responses/InvalidParametersExceptionResponse.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/persistence/mongo_db/MongoDB.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/utilities/LoggingUtils.java
Labels: enhancement, functionality

#16 Added endpoint to update ticket status
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/TicketController.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/entities/HttpParameters.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/persistence/Database.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/persistence/mongo_db/MongoDB.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/persistence/repository/TicketDao.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/persistence/repository/TicketDaoImpl.java
Labels: functionality

#18 Fixed code to send json response
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/TicketController.java
Labels: bug

#20 Added healthcheck endpoint
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/Healthcheck.java
Labels: enhancement

#22 Request body validated
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/TicketController.java
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/entities/Department.java
Labels: bug

#24 Fixed code to make dept case-insensitive and validated it
  src/main/java/com/helpdesk_ticketing_system/tickets_data_management/controllers/TicketController.java
Labels: bug
